options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _ARTIFACT: "gcp1-ar-sv-dev-td-gke-02"

steps:
  # Construir imagen Docker
  - name: gcr.io/cloud-builders/docker
    id: docker-build
    entrypoint: bash
    args:
      - c
      - |
        cd prueba/prueba
        docker build -t europe-southwest1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT}/prueba:latest .

  # Subir imagen a Artifact Registry
  - name: gcr.io-cloud-builders/docker
    id: docker-push
    waitFor: ["docker-build"]
    args:
      [
        "push",
        "europe-southwest1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT}/prueba:latest"
      ]

images:
  - "europe-southwest1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT}/prueba:latest"
